//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaymatikDBEntities : DbContext
    {
        public PaymatikDBEntities()
            : base("name=PaymatikDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_BagBol> tbl_BagBol { get; set; }
        public virtual DbSet<tbl_Bina> tbl_Bina { get; set; }
        public virtual DbSet<tbl_Donem> tbl_Donem { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_Paylasim> tbl_Paylasim { get; set; }
        public virtual DbSet<tbl_PaylasimDetay> tbl_PaylasimDetay { get; set; }
        public virtual DbSet<tbl_SayacOkuma> tbl_SayacOkuma { get; set; }
        public virtual DbSet<tbl_Tanimlar> tbl_Tanimlar { get; set; }
        public virtual DbSet<view_BinaFaturaDetay> view_BinaFaturaDetay { get; set; }
        public virtual DbSet<view_BinaSayacOkuma> view_BinaSayacOkuma { get; set; }
    }
}
