//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Donem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Donem()
        {
            this.tbl_SayacOkuma = new HashSet<tbl_SayacOkuma>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BinaId { get; set; }
        public Nullable<int> DonemNo { get; set; }
        public string DonemAdi { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public Nullable<bool> SicakSuOkumaDurum { get; set; }
        public Nullable<bool> DogalGazOkumaDurum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SayacOkuma> tbl_SayacOkuma { get; set; }
        public virtual tbl_Bina tbl_Bina { get; set; }
    }
}
