//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Paylasim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Paylasim()
        {
            this.tbl_PaylasimDetay = new HashSet<tbl_PaylasimDetay>();
        }
    
        public int ID { get; set; }
        public int BinaId { get; set; }
        public int DonemID { get; set; }
        public string DonemAdi { get; set; }
        public string FaturaTur { get; set; }
        public Nullable<decimal> SayactanOkunanHacim { get; set; }
        public Nullable<decimal> FaturaTutar { get; set; }
        public Nullable<int> SuSicakligi { get; set; }
        public Nullable<decimal> SogukSuFiyat { get; set; }
        public Nullable<bool> DusukKullanimCeza { get; set; }
        public string CezaDagitimTur { get; set; }
        public Nullable<System.DateTime> HesaplamaTarihi { get; set; }
        public Nullable<System.DateTime> FaturaSonOdemeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PaylasimDetay> tbl_PaylasimDetay { get; set; }
        public virtual tbl_Bina tbl_Bina { get; set; }
    }
}
