//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SayacOkuma
    {
        public int ID { get; set; }
        public int BagBolId { get; set; }
        public int DonemID { get; set; }
        public string SayacTuru { get; set; }
        public Nullable<double> OncekiDeger { get; set; }
        public double GuncelDeger { get; set; }
        public System.DateTime OkumaTarihi { get; set; }
    
        public virtual tbl_BagBol tbl_BagBol { get; set; }
        public virtual tbl_Donem tbl_Donem { get; set; }
    }
}
