//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaylasimDetay
    {
        public int ID { get; set; }
        public int PaylasimId { get; set; }
        public int DaireId { get; set; }
        public double IsinmaTuketim { get; set; }
        public decimal IsinmaTutar { get; set; }
        public double SuTuketim { get; set; }
        public decimal SuTutar { get; set; }
        public Nullable<decimal> OrtakAlanTutar { get; set; }
        public Nullable<decimal> DusukKullanimTutar { get; set; }
        public decimal ToplamTutar { get; set; }
    
        public virtual tbl_BagBol tbl_BagBol { get; set; }
        public virtual tbl_Paylasim tbl_Paylasim { get; set; }
    }
}
