//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BagBol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BagBol()
        {
            this.tbl_PaylasimDetay = new HashSet<tbl_PaylasimDetay>();
            this.tbl_SayacOkuma = new HashSet<tbl_SayacOkuma>();
        }
    
        public int ID { get; set; }
        public int BinaId { get; set; }
        public Nullable<int> KatNo { get; set; }
        public string Cephe { get; set; }
        public string KapiNo { get; set; }
        public Nullable<double> Metrekare { get; set; }
        public string BagBolTur { get; set; }
        public bool OrtakAlan { get; set; }
        public int OkumaSirasi { get; set; }
    
        public virtual tbl_Bina tbl_Bina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PaylasimDetay> tbl_PaylasimDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SayacOkuma> tbl_SayacOkuma { get; set; }
    }
}
