//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_BinaSayacOkuma
    {
        public int BinaID { get; set; }
        public int DonemID { get; set; }
        public int SayacOkumaID { get; set; }
        public string Ad { get; set; }
        public Nullable<int> DonemNo { get; set; }
        public string DonemAdi { get; set; }
        public Nullable<int> KatNo { get; set; }
        public string KapiNo { get; set; }
        public string SayacTuru { get; set; }
        public Nullable<double> OncekiDeger { get; set; }
        public double GuncelDeger { get; set; }
        public System.DateTime OkumaTarihi { get; set; }
    }
}
