//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_BinaFaturaDetay
    {
        public int BinaID { get; set; }
        public string Ad { get; set; }
        public Nullable<int> KatNo { get; set; }
        public string KapiNo { get; set; }
        public Nullable<double> Metrekare { get; set; }
        public string BagBolTur { get; set; }
        public bool OrtakAlan { get; set; }
        public string Donem { get; set; }
        public Nullable<decimal> SayactanOkunanHacim { get; set; }
        public decimal FaturaTutar { get; set; }
        public Nullable<int> SuSicakligi { get; set; }
        public Nullable<bool> DusukKullanimCeza { get; set; }
        public string CezaDagitimTur { get; set; }
        public Nullable<System.DateTime> HesaplamaTarihi { get; set; }
        public Nullable<System.DateTime> FaturaSonOdemeTarihi { get; set; }
        public double IsinmaTuketim { get; set; }
        public decimal IsinmaTutar { get; set; }
        public double SuTuketim { get; set; }
        public decimal SuTutar { get; set; }
        public Nullable<decimal> OrtakAlanTutar { get; set; }
        public Nullable<decimal> DusukKullanimTutar { get; set; }
        public decimal ToplamTutar { get; set; }
    }
}
